### ISSUE TITLE
What do macros do?

### ISSUE THREAD

**Issue by backfromhiatus** [ModPunchtree/URCL#6]
Are macros just used to define values, or are like x86 asm macros? Im following jonesforth so id like to know, thanks!

**Comment by ModPunchtree** [comment]
Macros are described in the URCL V1.5.0 documentation as:
```
All macros are prepended with @. For example:
@DEFINE TEST 2
Individual macros are not defined in URCL as they are completely up to the particular URCL interpreter to define. This
is to enable different interpreters to define macros to suit their own needs.
```
Meaning specific macros are not strictly defined in the documentation.

A common example of a macro that a URCL interpreter may support, is an @DEFINE macro which simply defines one token as another and those tokens are substituted before interpreting the code. This enables you to assign different names to the registers or assign a name to a constant (number).
